#!/usr/bin/env ruby

require 'sass'
require 'pathname'

class SCSSProcessor
  SCSS_FILES = ["./master.scss", "./abbreviations.scss"]
  OUTPUT_FILE = "~/Documents/Anki/e/collection.media/_master.css"
  TMP_CONCAT_FILE = "/tmp/concatenated_anki.scss"

  def self.run
    build_concatenated_scss_file
    begin
      Sass.compile_file(TMP_CONCAT_FILE, css_output_file)
    ensure
      clean_up
    end
  end

  private

  def self.build_concatenated_scss_file
    File.open(TMP_CONCAT_FILE, 'a') do |concated_file|
      SCSS_FILES.each do |scss_file|
        File.foreach(scss_file) do |line|
          concated_file.write(line)
        end
      end
    end
  end

  def self.css_output_file
    Pathname.new(OUTPUT_FILE).expand_path
  end

  def self.clean_up
    File.delete(TMP_CONCAT_FILE)
  end
end

if $0 == __FILE__ then
  SCSSProcessor.run
end
