#!/usr/bin/env ruby

require 'sass'
require 'pathname'

# main class to be run for compile the CSS and moving it to Anki
class SCSSProcessor
  SCSS_FILES = ["./colors.scss", "./master.scss", "./abbreviations.scss", "./column-flex-table.scss", "./code.scss", "./japanese.scss", "./sanskrit.scss", "./chinese.scss", "./english.scss", "./nullify-ankidroid-night-mode.scss"]
  OUTPUT_FILENAME_BASE = "_master"
  TMP_CONCAT_FILE = "/tmp/concatenated_anki.scss"

  def self.run
    set_load_paths
    build_concatenated_scss_file
    begin
      rm_old_css
      compile_sass_files
    ensure
      clean_up
    end
  end

  private

  def self.set_load_paths
    Sass.load_paths << "./japanese-definitions"
  end

  def self.build_concatenated_scss_file
    File.open(TMP_CONCAT_FILE, 'a') do |concated_file|
      SCSS_FILES.each do |scss_file|
        File.foreach(scss_file) do |line|
          concated_file.write(line)
        end
      end
    end
  end

  def self.rm_old_css
    Dir.glob(anki_css_filepath("-*")).each do |path|
      File.delete(path)
    end
  end

  def self.compile_sass_files
    [master_css_output_filepath, master_time_tagged_css_output_filepath].each do |output_filepath|
      Sass.compile_file(TMP_CONCAT_FILE, output_filepath)
    end
  end

  def self.clean_up
    File.delete(TMP_CONCAT_FILE)
  end

  def self.master_css_output_filepath
    anki_css_filepath
  end

  def self.master_time_tagged_css_output_filepath
    current_secs = Time.new.to_i
    puts current_secs
    anki_css_filepath("-#{current_secs}")
  end

  def self.anki_css_filepath(filepath_append = "")
    output_dir + (OUTPUT_FILENAME_BASE + "#{filepath_append}.css")
  end

  def self.output_dir
    programs_data_dir + "Anki2/e/collection.media"
  end

  def self.programs_data_dir
    os_category = `uname -a`.split(" ").first
    if os_category == "Linux"
      Pathname.new("~/.local/share/").expand_path
    elsif os_category == "Darwin"
      Pathname.new("~/Library/Application Support/").expand_path
    else
      raise NotImplementedError, "finding the anki data dir is only implemented for Mac and Linux"
    end
  end
end

if $0 == __FILE__ then
  SCSSProcessor.run
end
